project:
  type: website
  output-dir: docs

website:
  title: "ABopsC"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: ../temp/pages/about.html
        text: About ABopsC
      - href: ../temp/pages/scavenger.html
        text: Scavenger Hunt
      - href: ../temp/pages/lesson.html
        text: Lesson
      - href: ../temp/pages/labs.html
        text: Labs
      - href: ../temp/pages/scoring.html
        text: Scores
    right:
      - href: ../temp/pages/userControl.html
        text: Account
  page-footer:
    background: $secondary
    foreground: white
    border: $button-border
    left:
      - text: "Lesson"
        href: ../temp/pages/lesson.html
      - text: "Scavenger Hunt"
        href: ../temp/pages/scavenger.html
      - text: "Labs"
        href: ../temp/pages/labs.html
    right:
      - text: "Github"
        href: "https://github.com/deimie/temp"


format:
  html:
    theme: 
      - flatly
      - styles.scss

