project:
  type: website
  output-dir: docs

website:
  title: "ABopsC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - /pages/about.qmd
    right:
      - href: userControl.md
        text: Account

format:
  html:
    theme: 
      - flatly
      - styles.scss

