project:
  type: website
  output-dir: docs

website:
  title: "ABopsC"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: ../pages/about.html
        text: About ABopsC
      - href: ../pages/scavenger.html
        text: Scavenger Hunt
      - href: ../pages/lesson.html
        text: Lesson
      - href: ../pages/labs.html
        text: Labs
      - href: ../pages/scoring.html
        text: Scores
    right:
      - href: ../pages/userControl.html
        text: Account

format:
  html:
    theme: 
      - flatly
      - styles.scss

body-header: |
  "yass queen"

