project:
  type: website
  output-dir: docs

website:
  title: "temp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pages/about.qmd

format:
  html:
    theme: 
      - flatly
      - styles.scss

