name: Quarto

on:
  push:
    branches: [master]

jobs:
  Quarto Commands:
    runs-on: ubuntu-latest

    steps:
      - name: Quarto Commands
      - run: quarto render
      - run: git push
      - run: quarto publish gh-pages
