name: Quarto

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Quarto Commands
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 0.3.71
          script: |
            quarto render
            git push
            quarto publish gh-pages
            git push
