name: Quarto

on:
  push:
    branches: [master]

jobs:
  Quarto Commands:
    runs-on: ubuntu-latest

    steps:
      - name: Quarto Commands
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 0.3.71
        run: quarto render
        run: git push
        run: quarto publish gh-pages
        run: git push
